import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/providers";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TOK | Tokenization for Everyone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <AppProviders>
        {children}
        <Toaster 
          position="top-right"
          toastOptions={{
            // Estilo base para todos
            style: { padding: '16px' },
            classNames: {
              // Éxito: bg primary, texto blanco
              success: 'bg-primary text-white border-none',
              // Error: bg blanco, borde primary (o red según decidas)
              error: 'bg-white border-2 border-primary text-black',
            },
          }}
        />
        </AppProviders>
      </body>
    </html>
  );
}
